import unittest

from ai.generation_errors import (
    moderation_failure, public_generation_error, transient_gateway_failure,
)


class GenerationErrorTest(unittest.TestCase):
    def test_moderation_error_becomes_actionable(self):
        value = moderation_failure(
            "GPT-Image 编辑失败 400: Your request was rejected by the safety system. "
            "request ID f4ccc117-3d69-4fe5-92a9-db1fce8fa272; code moderation_blocked")
        self.assertEqual("IMAGE_SAFETY_REVIEW", value["code"])
        self.assertEqual("f4ccc117-3d69-4fe5-92a9-db1fce8fa272", value["request_id"])
        self.assertNotIn("GPT-Image 编辑失败 400", value["message"])

    def test_other_errors_are_not_mislabeled(self):
        self.assertIsNone(moderation_failure("connection timeout"))

    def test_cloudfront_page_becomes_retryable_error(self):
        value = transient_gateway_failure(
            "504 Gateway Timeout ERROR Generated by cloudfront Request ID: abc_DEF-123456")
        self.assertEqual("UPSTREAM_504", value["code"])
        self.assertEqual("abc_DEF-123456", value["request_id"])
        self.assertNotIn("CloudFront", value["message"])

    def test_rate_limit_payload_becomes_plain_chinese(self):
        value = public_generation_error(
            "Ark HTTP 429 RateLimitReached: request ID abcdef12-3456")
        self.assertIn("请求过于频繁", value)
        self.assertIn("abcdef12-3456", value)
        self.assertNotIn("RateLimitReached", value)

    def test_invalid_provider_json_is_not_shown_verbatim(self):
        value = public_generation_error(
            "Ark HTTP 400 InvalidParameter: content[0].video_url invalid")
        self.assertIn("参数不符合模型要求", value)
        self.assertNotIn("content[0]", value)


if __name__ == "__main__":
    unittest.main()
