import unittest

from ai.generation_errors import moderation_failure, transient_gateway_failure


class GenerationErrorTest(unittest.TestCase):
    def test_moderation_error_becomes_actionable(self):
        value = moderation_failure(
            "GPT-Image 编辑失败 400: Your request was rejected by the safety system. "
            "request ID f4ccc117-3d69-4fe5-92a9-db1fce8fa272; code moderation_blocked")
        self.assertEqual("IMAGE_SAFETY_REVIEW", value["code"])
        self.assertEqual("f4ccc117-3d69-4fe5-92a9-db1fce8fa272", value["request_id"])
        self.assertNotIn("GPT-Image 编辑失败 400", value["message"])

    def test_other_errors_are_not_mislabeled(self):
        self.assertIsNone(moderation_failure("connection timeout"))

    def test_cloudfront_page_becomes_retryable_error(self):
        value = transient_gateway_failure(
            "504 Gateway Timeout ERROR Generated by cloudfront Request ID: abc_DEF-123456")
        self.assertEqual("UPSTREAM_504", value["code"])
        self.assertEqual("abc_DEF-123456", value["request_id"])
        self.assertNotIn("CloudFront", value["message"])


if __name__ == "__main__":
    unittest.main()
